server:
  port: 80
spring:
  application:
    # 服务别名
    name: cloud-consumer-order
  cloud:
    zookeeper:
      # 注册到zookeeper地址
      connect-string: 192.168.238.66:2181  #单机版
#    connect-string: 192.168.238.66:2888,192.168.238.66:2889,192.168.238.66:2890