server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册Eureka服务器的微服务
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ziyu-L/MySpringCloudConfig.git #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - MySpringCloudConfig
      #读取分支
      label: master
#RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#RabbitMQ相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"

#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka