server:
  port: 80

spring:
  application:
    name: cloud-consumer-order1
  cloud:
    consul:
    # consul注册中心地址
      host: 192.168.238.66
      port: 8500
      discovery:
#        hostname: 192.168.238.66
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true