server:
  # consul服务端口
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      #      host: localhost
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

