#server:
#  # consul服务端口
#  port: 8007
#spring:
#  application:
#    name: cloud-provider-payment
#  cloud:
#    consul:
#      # consul注册中心地址
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        hostname: localhost
#        service-name: ${spring.application.name}
#        heartbeat:
#          enabled: true

server:
  # consul服务端口
  port: 8007
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.238.66
      port: 8500
      discovery:
        #        hostname: localhost.localdomain
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true